### Create lesson
POST {{baseUrl}}/api/lesson
Content-Type: application/json
Accept: application/json

{
  "lessonName": "Intro lesson",
  "date": "2026-02-06T08:00:00Z"
}

> {%
    client.global.set("lessonID", response.body.lessonID);
%}

### Get lesson
GET {{baseUrl}}/api/lesson/{{lessonID}}
Accept: application/json

### Update lesson
PUT {{baseUrl}}/api/lesson/{{lessonID}}
Content-Type: application/json
Accept: application/json

{
  "lessonName": "Updated lesson name",
  "date": "2026-02-07T08:00:00Z"
}

### Delete lesson
DELETE {{baseUrl}}/api/lesson/{{lessonID}}
Accept: application/json
