### Create student
POST http://localhost:8081/api/student
Content-Type: application/json
Accept: application/json

{
  "firstName": "Test",
  "lastName": "student",
  "email": "test.userhttp2@example.com",
  "password": "secretpassword"
}

> {%
  client.global.set("studentID", response.body.studentID);
%}

### Get student
GET {{baseUrl}}/api/student/{{studentID}}
Accept: application/json

### Update student
PUT {{baseUrl}}/api/student/{{studentID}}
Content-Type: application/json
Accept: application/json

{
  "firstName": "updated",
  "lastName": "name"
}

### Delete student
DELETE {{baseUrl}}/api/student/{{studentID}}
