### Create teacher
POST {{baseUrl}}/api/teacher
Content-Type: application/json
Accept: application/json

{
  "firstName": "Test",
  "lastName": "teacher",
  "email": "test.teacher@example.com",
  "password": "secretpassword",
  "isAdmin": true
}

> {%
    client.global.set("teacherID", response.body.teacherID);
%}

### Get teacher
GET {{baseUrl}}/api/teacher/{{teacherID}}
Accept: application/json

### Update teacher
PUT {{baseUrl}}/api/teacher/{{teacherID}}
Content-Type: application/json
Accept: application/json

{
  "firstName": "updated",
  "lastName": "teacher",
  "isAdmin": false
}

### Delete teacher
DELETE {{baseUrl}}/api/teacher/{{teacherID}}
