DROP DATABASE IF EXISTS attendance_test;
CREATE DATABASE IF NOT EXISTS attendance_test;
USE attendance_test;
CREATE TABLE STUDENT
(
  StudentID INT NOT NULL AUTO_INCREMENT,
  Email VARCHAR(32) NOT NULL,
  Name VARCHAR(32) NOT NULL,
  Password VARCHAR(32) NOT NULL,
  PRIMARY KEY (StudentID)
);

CREATE TABLE COURSE
(
  CourseID INT NOT NULL,
  CourseName INT NOT NULL,
  PRIMARY KEY (CourseID)
);

CREATE TABLE LESSON
(
  LessonID INT NOT NULL,
  Date INT NOT NULL,
  Name INT NOT NULL,
  CourseID INT NOT NULL,
  PRIMARY KEY (LessonID),
  FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);

CREATE TABLE TEACHER
(
  TeacherID INT NOT NULL,
  Email INT NOT NULL,
  Name INT NOT NULL,
  Password INT NOT NULL,
  PRIMARY KEY (TeacherID)
);

CREATE TABLE ASSIGNMENT
(
  AssignmentID INT NOT NULL,
  AssDescription INT NOT NULL,
  AssName INT NOT NULL,
  CourseID INT NOT NULL,
  PRIMARY KEY (AssignmentID),
  FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);

CREATE TABLE ATTENDS
(
  Present INT NOT NULL,
  ReasonForAbsence INT NOT NULL,
  LessonID INT NOT NULL,
  StudentID INT NOT NULL,
  PRIMARY KEY (LessonID, StudentID),
  FOREIGN KEY (LessonID) REFERENCES LESSON(LessonID),
  FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID)
);

CREATE TABLE TEACHES
(
  LessonID INT NOT NULL,
  TeacherID INT NOT NULL,
  PRIMARY KEY (LessonID, TeacherID),
  FOREIGN KEY (LessonID) REFERENCES LESSON(LessonID),
  FOREIGN KEY (TeacherID) REFERENCES TEACHER(TeacherID)
);

CREATE TABLE DOES
(
  Grade INT NOT NULL,
  StudentID INT NOT NULL,
  AssignmentID INT NOT NULL,
  PRIMARY KEY (StudentID, AssignmentID),
  FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID),
  FOREIGN KEY (AssignmentID) REFERENCES ASSIGNMENT(AssignmentID)
);

CREATE TABLE BELONGSTO
(
  Grade INT NOT NULL,
  StudentID INT NOT NULL,
  CourseID INT NOT NULL,
  PRIMARY KEY (StudentID, CourseID),
  FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID),
  FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);

CREATE TABLE RELATIONSHIP
(
  TeacherID INT NOT NULL,
  CourseID INT NOT NULL,
  PRIMARY KEY (TeacherID, CourseID),
  FOREIGN KEY (TeacherID) REFERENCES TEACHER(TeacherID),
  FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);
